import {
 
  imprimante1,
  imprimante2,
  imprimante4,
  imprimante5,
  imprimante6,
  imprimante7,
  imprimante8,
  imprimante9,
  encre1,
  encre2,
  encre3,
  encre4,
  ruban1,
  ruban2,
  ruban3,
  ruban4,
  bag,
  bac2,
  bac3,
  bac4,
  pdf1,
   fashion1,
   Fashion2,
  Electronictv,
  Furniture,
  Furniture2,
  laptopbag1,
  Electronic1,
  Mobile,
 
  
  
  Fashion3,
} from "../assets/images/index";

import "./style.css";

// =================== NavBarList Start here ====================
export const navBarList = [
  {
    _id: 1001,
    title: "Home",
    link: "/",
  },
  {
    _id: 1002,
    title: "Shop",
    link: "/shop",
  },
  {
    _id: 1003,
    title: "About",
    link: "/about",
  },
  {
    _id: 1004,
    title: "Contact",
    link: "contact",
  },
  {
    _id: 1005,
    title: "Journal",
    link: "/journal",
  },
];
// =================== NavBarList End here ======================
// =================== Special Offer data Start here ============
export const SplOfferData = [
  {
    _id: "201",
    img: imprimante1,
    productName: "imprimante",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "imprimante",
  },
  {
    _id: "202",
    img: imprimante2,
    productName: "imprimante",
    price: "180.00",
    color: "Gray",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "imprimante",
  },
  {
    _id: "203",
    img: imprimante4,
    productName: "imprimante",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "imprimante",
  },
  {
    _id: "204",
    img: imprimante5,
    productName: "imprimante",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "imprimante",
  },
  {
    _id: "205",
    img: imprimante6,
    productName: "imprimante",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "imprimante",
  },
  {
    _id: "206",
    img: imprimante7,
    productName: "imprimante",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "imprimante",
  },
  {
    _id: "207",
    img: imprimante8,
    productName: "imprimante",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "imprimante",
  },
  {
    _id: "208",
    img: imprimante9,
    productName: "imprimante",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "imprimante",
  },
  {
    _id: "209",
    img: encre1,
    productName: "encre",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "ancre",
  },
  {
    _id: "210",
    img: encre2,
    productName: "encre",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "ancre",
  },
  {
    _id: "211",
    img: encre3,
    productName: "encre",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "ancre",
  },
  {
    _id: "212",
    img: encre4,
    productName: "encre",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "ancre",
  },
  {
    _id: "213",
    img: ruban1,
    productName: "Ruban",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Ruban",
  },
  {
    _id: "214",
    img: ruban2,
    productName: "Ruban",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Ruban",
  },
  {
    _id: "215",
    img: ruban3,
    productName: "Ruban",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Ruban",
  },
  {
    _id: "216",
    img: ruban4,
    productName: "Ruban",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Ruban",
  },
  {
    _id: "217",
    img: bag,
    productName: "Bac de dechet",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Bags & School bags",
  },
  {
    _id: "219",
    img: bac2,
    productName: "Bac de dechet",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Bac",
  },
  {
    _id: "220",
    img: bac3,
    productName: "Bac de dechet",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Bac",
  },
  {
    _id: "221",
    img: bac4,
    productName: "Bac de dechet",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Bac",
  },
];
// =================== Special Offer data End here ==============

// =================== PaginationItems Start here ===============

export const paginationItems = [
  {
    _id: "201",
    img: fashion1,
    productName: "Fashion Denim jacket",
    price: "35.00",
    color: "Blue",
    badge: true,
    brand: "H&M",
    des: "Blue color denim jacket ",
    cat: "Fashion",
    pdf: pdf1,
    Features: [
      { label: "Brand", value: "H&m " },
      { label: "Fabric ", value: "Cotton fabric" },

      { label: "Sleeve", value: "Full sleeve with collar      " },
      { label: "Pair with", value: "Denim jeans " },
      
    ],
  },
  {
    _id: "202",
    img: Fashion2,
    productName: "Fashion pink Mens Tshirt",
    price: "450",
    color: "Pink",
    badge: true,
    brand: "H&M",
    des: "Mens Tshirt pink branded with high quality fabric, and color",
    cat: "Fashion",
    pdf: pdf1,
    Features: [
      { label: "Brand", value: "H&m " },
      { label: "Fabric ", value: "Cotton fabric" },

      { label: "Sleeve", value: "Full sleeve with collar      " },
      { label: "Pair with", value: "Denim jeans "  },

      
    ],
  },

  {
    _id: "203",
    img: Electronic1,
    productName: "Electronic Smart Watch",
    price: "450",
    color: "Pink",
    badge: true,
    brand: "Apple",
    des: "Acnos® Brand Premium 7 Colors Strap Display Fashionable Children Kids Digital Watches Waterproof Sports Square Electronic Led Watch for Kids Boy Baby Girls Digital Watch for Kids ",
    cat: "Electronics",
    pdf: pdf1,
    Features: [
      { label: "Movement: ", value: ": Analogue Digital watch for men " },
      { label: "Wear-ability ", value: " Sport, Casual, Fashion, Luxury, Party-Wear, Wrist, Weeding kids watches for boys| Look : Smart Watch | Gender :Men's & Boy's | Designer For Young People & Teenagers of India mens watch" },

      {
        label: "Strap Material :",
        value: " High Quality Premium PU watch for Boy's and Girl's ",
      },
      
      { label: "Item Dimension      ", value: "6 x 8 x 10 Millimeter" },
      
     
    ],
  },
  {
    _id: "2005",
    img: Electronictv,
    productName: "Electronic Sony tv",
    price: "450",
    color: "Black",
    badge: true,
    brand: "Apple",
    des: "Balaji Traders is a distinguished manufacturer offering an enormous consignment of Electric Kettle, Juicer Mixer, Hand Blender, Mixer Chopper, Electric Geyser, Electric Iron, LCD TV, LED TV, LED Light, Roti Maker. Immensely acclaimed in the industry owing to their preciseness, these are presented by us in standard and modified forms to our clients. To add, only optimum class material is utilized in their production. These presented by us in various provisions, these are inspected sternly to retain their optimum quality",
    cat: "Electronics",
    pdf: pdf1,
    Features: [
      { label: " Screen Size	", value:"50 inches "      },
      { label: "Brand	", value: "Sony   " },
      { label: "Display Technology	", value: "LED   " },
      { label: "Resolution	", value: "4k     " },

    ],
  },

  {
    _id: "20005",
    img: Mobile,
    productName: "Iphone Mobile ",
    price: "450",
    color: "Grey",
    badge: true,
    brand: "Apple",
    des: "Iphone 15 pro 16 GB(RAM),256 GB Storage  ",
    cat: "Electronics",
    pdf: pdf1,
    Features: [
      { label: "Display	", value: "6.67 Inches; 120 Hz 3D Curved AMOLED 1.5K Display with Corning Gorilla Glass Victus; Resolution: 2712 x 1220 Pixels; Dolby Vision, Adaptive HDR 10+, 68.7billion colors, 1800nit"   },
      { label: "Processor	", value: "Mediatek Dimensity 7200 Octa-core Processor (Based 4nm Architecture) ; Up to 2.8 GHz   " },
      { label: "Camera:", value: "200MP Main Camera with Samsung ISOCELL HP3 sensor (OIS + EIS supported), 8MP Ultrawide and 2MP Macro | 16MP Front (Selfie) Camera; 7P lens, Dual LED Flash     " },
      { label: "Battery		", value:" 120W HyperCharge Fast-charging with 5000 mAh large battery | 120W Adapter In-box and Type-C Connectivity    " },
          ],
  },

  {
    _id: "206",
    img: Furniture,
    productName: "Furniture Bed Wooden ",
    price: "450",
    color: "Brown",
    badge: true,
    
    des: "Lorem",
    cat: "Furniture",
    pdf: pdf1,
    Features: [
    
    ]
  },

  {
    _id: "207",
    img: Furniture2,
    productName: "Woodeb Round table ",
    price: "450",
    color: "White",
    badge: true,
    brand: "Pantum",
    des: "",
    cat: "Furniture",
    pdf: pdf1,

  },

  {
    _id: "208",
    img: laptopbag1,
    productName: "Laptop Bag",
    price: "450",
    color: "black",
    badge: true,
    brand: "Skybag",
    des: "Bag ",
    cat: "Bag & School Bags",
    pdf: pdf1,
   
  },
  {
    _id: "233",
    img: Fashion3,
    productName: "Kids Clothing ",
    price: "450",
    color: "White",
    badge: true,
    brand: "H&M",
    des: "Kids branded Clothes",
    cat: "Fashion",
    pdf: pdf1,
    ficheTech: [],
  },
  {
    _id: "220",
    img: bag,
    brand: "Skybag",
    productName: "Blue School bag",
    price: "25.00",
    color: "Blue",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Bag & School bags",
  },
  {
    _id: "221",
    img: bac4,
    productName: "Refilling Printing pipe",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Bac",
  },
  {
    _id: "220",
    img: bag,
    productName: "Blue School bag",
    price: "25.00",
    color: "Blue",
    badge: true,
    brand: "Skybag",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Bag & School Bags",
  },
  {
    _id: "208",
    img: laptopbag1,
    productName: "Laptop Bag",
    price: "450",
    color: "black",
    badge: true,
    brand: "Skybag",
    des: "Bag ",
    cat: "Bag & School Bags",
    pdf: pdf1,
   
  },
  {
    _id: "207",
    img: Furniture2,
    productName: "Wooden Round table ",
    price: "450",
    color: "White",
    badge: true,
    brand: "Pantum",
    des: "",
    cat: "Furniture",
    pdf: pdf1,

  },
  
];
